name: Deploy NestJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            script: |
             set -e

             export PATH="$HOME/.local/share/pnpm/bin:$PATH"

             cd ~/nest-app

             git pull origin main
             pnpm install --frozen-lockfile
             pnpm test
             pnpm build

             pm2 restart nest-app

             echo "Checking PM2..."
             pm2 status

             echo "Recent logs..."
             pm2 logs nest-app --lines 20 --nostream
