name: Deploy NestJS

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.image.outputs.name }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set image name
        id: image
        run: echo "name=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image.outputs.name }}:latest
            ${{ steps.image.outputs.name }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          envs: IMAGE_NAME IMAGE_TAG GHCR_USERNAME GHCR_TOKEN

          script: |
            set -e

            echo "Logging in to GitHub Container Registry..."

            echo "$GHCR_TOKEN" | docker login ghcr.io \
              --username "$GHCR_USERNAME" \
              --password-stdin

            echo "Pulling Docker image..."

            docker pull "$IMAGE_NAME:$IMAGE_TAG"

            echo "Removing old container..."

            docker rm -f nest-app || true

            echo "Starting new container..."

            docker run -d \
              --name nest-app \
              --restart unless-stopped \
              -p 3000:3000 \
              "$IMAGE_NAME:$IMAGE_TAG"

            echo "Logging out from GHCR..."

            docker logout ghcr.io

            echo "Cleaning unused images..."

            docker image prune -f

            echo "Container status..."

            docker ps --filter name=nest-app

            echo "Application logs..."

            docker logs --tail 20 nest-app

        env:
          IMAGE_NAME: ${{ needs.build.outputs.image }}
          IMAGE_TAG: ${{ github.sha }}
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
